---
title: "Top 25 US airports passenger traffic"
author: "Gvaurs"
date: "27/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
setwd("C:\\Users\\Geraud\\datasciencecoursera\\InteractiveMapExample")
```

## Description

This document describes the 2019 passenger traffic for the top 25 US airports.

```{r data, echo=FALSE, }
airports <- read.csv('us_airport_data.csv', sep = ';', stringsAsFactors = FALSE)
airports$TrafficGroup <- cut(airports$Traffic, c(0,30000000, 45000000, 60000000, 75000000, 90000000, 105000000, 115000000))
levels(airports$TrafficGroup) <- c("< 30 M", "< 45 M", "< 60 M", "< 75 M", "< 90 M", "< 105 M", "> 105 M") 
```

## Top 25 US airports map

```{r map, echo=FALSE, out.width='100%'}
factpal <- colorFactor(heat.colors(7), airports$TrafficGroup, reverse = TRUE, ordered = TRUE)

m <- leaflet() %>%
    addTiles() %>%
    addCircles(lat=airports$Latitude, lng=airports$Longitude, radius=airports$Traffic * 0.001, weight=1, fillOpacity = 0.8, color=factpal(airports$TrafficGroup), popup=paste("Airport:", airports$Name, "<br>", "Pax traffic (2019):", format(airports$Traffic, big.mark=',' ))) %>%
    addLegend(colors=factpal(levels(airports$TrafficGroup)), labels=levels(airports$TrafficGroup))
m
```