---
title: "US States 2020 population estimate"
author: "Gvaurs"
date: "27/12/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(plotly)
library(rjson)
```

## Description

- This presentation provides an interactive map depicting the US population estimate by state in 2020
- Data originates from the US Census Bureau https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/national/totals/nst-est2020.csv

## US 2020 Population estimate Map

```{r data_states, echo = FALSE}
url <- 'https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json'
states <- fromJSON(file=url)
states$features <- lapply(states$features, function(state){state$id <- as.integer(state$id); state})
```

```{r data_pop, echo = FALSE}
pop <- read.csv('https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/national/totals/nst-est2020.csv')
pop <- pop[pop$SUMLEV == 40, c('STATE', 'NAME', 'POPESTIMATE2020')]
pop$HOVER <- with(pop, paste(NAME, '<br>',"Pop: ", format(POPESTIMATE2020, big.mark = ",")))
```

```{r plot, echo = FALSE, warning=FALSE}
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = FALSE,
  lakecolor = toRGB('lightblue')
)
fig <- plot_ly()
fig <- fig %>% add_trace(
    type="choropleth",
    geojson=states,
    locations=pop$STATE,
    text=pop$HOVER,
    z=pop$POPESTIMATE2020,
    colorscale="Reds",
    hoverinfo = 'text',
    autocolorscale=FALSE
  )
fig <- fig %>% colorbar(title = "2020 population estimate")

fig <- fig %>% layout(
    geo = g
  )

fig
```